package com.cheers.dataobject;

import java.math.BigDecimal;

public class ClothDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth.id
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth.imgUrl
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth.price
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth.year
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloth.comment
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth.id
     *
     * @return the value of cloth.id
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth.id
     *
     * @param id the value for cloth.id
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth.imgUrl
     *
     * @return the value of cloth.imgUrl
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth.imgUrl
     *
     * @param imgurl the value for cloth.imgUrl
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    public void setImgUrl(String imgurl) {
        this.imgUrl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth.price
     *
     * @return the value of cloth.price
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth.price
     *
     * @param price the value for cloth.price
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth.year
     *
     * @return the value of cloth.year
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth.year
     *
     * @param year the value for cloth.year
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloth.comment
     *
     * @return the value of cloth.comment
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloth.comment
     *
     * @param comment the value for cloth.comment
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}