package com.cheers.dataobject;

import java.util.Date;

public class OotdDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ootd.id
     *
     * @mbg.generated Thu May 25 00:21:57 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ootd.imgUrl
     *
     * @mbg.generated Thu May 25 00:21:57 CST 2023
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ootd.date
     *
     * @mbg.generated Thu May 25 00:21:57 CST 2023
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ootd.comment
     *
     * @mbg.generated Thu May 25 00:21:57 CST 2023
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ootd.id
     *
     * @return the value of ootd.id
     *
     * @mbg.generated Thu May 25 00:21:57 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ootd.id
     *
     * @param id the value for ootd.id
     *
     * @mbg.generated Thu May 25 00:21:57 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ootd.imgUrl
     *
     * @return the value of ootd.imgUrl
     *
     * @mbg.generated Thu May 25 00:21:57 CST 2023
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ootd.imgUrl
     *
     * @param imgUrl the value for ootd.imgUrl
     *
     * @mbg.generated Thu May 25 00:21:57 CST 2023
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ootd.date
     *
     * @return the value of ootd.date
     *
     * @mbg.generated Thu May 25 00:21:57 CST 2023
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ootd.date
     *
     * @param date the value for ootd.date
     *
     * @mbg.generated Thu May 25 00:21:57 CST 2023
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ootd.comment
     *
     * @return the value of ootd.comment
     *
     * @mbg.generated Thu May 25 00:21:57 CST 2023
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ootd.comment
     *
     * @param comment the value for ootd.comment
     *
     * @mbg.generated Thu May 25 00:21:57 CST 2023
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}