package com.cheers.dao;

import com.cheers.dataobject.ClothDO;

public interface ClothDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloth
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloth
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    int insert(ClothDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloth
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    int insertSelective(ClothDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloth
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    ClothDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloth
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    int updateByPrimaryKeySelective(ClothDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloth
     *
     * @mbg.generated Thu May 25 00:18:11 CST 2023
     */
    int updateByPrimaryKey(ClothDO record);
}